### PR TITLE
fix modified properties of moved stage being reverted.

### LINKED ISSUE #72: moving stages up and down reverts other changes
https://github.com/FirstLegoLeagueIL/fllscoring/blob/fb69556752674da78ba47f8e7420b976a915d931/src/js/views/settings.js#L66-L72

if one increases number of rounds in some stage, and then clicks "up" or "down" (without saving first), then the change in the number of rounds is reverted.

### PR DESCRIPTION
**Pull request by itamargreen**
this fixed #72 

the problem was the mismatch between `_rawStages` and the `$scope.stages` array. 

changes made in the stages (name or round number) were only changing `$scope.stages` and so when `moveStage` is called in the `ng-stages` service, those changes are lost.

### CODE REVIEW

File: src/js/services/ng-stages.js [hunk 1]
```diff
@@ -125,6 +125,9 @@ define('services/ng-stages',[
         Stages.prototype.moveStage = function(stage,steps) {
             var oldIndex = stage.index;
             var rawStage = this._rawStages[oldIndex];
+            Object.keys(rawStage).forEach((key)=>{
+                rawStage[key] = stage[key];
```
Comment (idanstark42) [inline src/js/services/ng-stages.js]: Add a comment. This seems unnecessary to someone who doesn't know the issue

Comment (itamargreen) [reply src/js/services/ng-stages.js]: sure
