### PR TITLE
Fixed importing Brian Lee's teams csv

### LINKED ISSUE #114: Teams import from .csv file sometimes doesn't import all teams
With the attached .csv file, when dropping into paste box, not all teams are in list of teams to import 
### Paste box
Team Number,Team Name
1606,Pirate Hogs
3007,Batteries
1585,SMS PUMAS 2
1439,Sea Urchins
1587,Sky Surfing Geeks

### Teams to import box
1585 | SMS PUMAS 2
1439 | Sea Urchins
1587 | Sky Surfing Geeks

Pressing Ok imports the 3 teams only.
[short team list with header.zip](https://github.com/FirstLegoLeagueIL/fllscoring/files/1503228/short.team.list.with.header.zip)

### PR DESCRIPTION
**Pull request by ThinkRedstone**
I moved the special case matching to the upload function, since the responsibility of the upload function is to set all the fields with the correct values to import teams from a csv file.

This change adds to @idanstark42 's matching of Brian Lee's csv format by also using the number of teams specified in the file to discard the irrelevant data at the end of the file.

Fixes #114

### CODE REVIEW

File: src/js/controllers/TeamImportDialogController.js [hunk 1]
```diff
@@ -63,10 +55,23 @@ define('controllers/TeamImportDialogController', [
...
+                reader.onload = (event) => { //no need to explicitly call parseData(), because it will trigger on it's own when we change $scope.importRaw
+                    // Checking special case for Brian Lee's scheduler program
+                    var data = event.target.result;
+                    var brianLeesFormattedData = data.match(BRIAN_LEES_SCHEDULER_FORMAT);
+                    if (brianLeesFormattedData) {
+                        $scope.useCustomDelimiter = true;
+                        $scope.delimiter = BRIAN_LEES_SCHEDULER_DELIMITER;
+                        $scope.headerLength = 0;
+                        var teamCount = parseInt(brianLeesFormattedData[1]); //regex has two group matches: the first matches the team count in the file
+                        var lines = brianLeesFormattedData[2].match(/[^\r\n]+/g);//the second group matchs the rest of the file, without the header- but including some other irrelevant data in the end
```
Comment (idanstark42) [inline src/js/controllers/TeamImportDialogController.js]: Why not use `split` here? It's cleaner then `match`. If you decide to use `match` anyway, you must check if the result is `null`, otherwise an unexpected exception will be thrown.

**Comment by ThinkRedstone** [comment]
I didn't plan to specifically, it just that it seemed odd to me to have parseData be responsible to setting up the needed variables to parse a csv file; And it was hard for me to imagine someone pasting a giant csv file into the text box.

**Comment by idanstark42** [comment]
Sounds good. Just making sure you tested it after switing to `split`, since it works differently from `match`, and should yield different results with the same regex

**Comment by ThinkRedstone** [comment]
Yeah, I'm not sure why the original regex doesn't work, so I switched to just splitting on a newline
